### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by ryrun** [comment]
Thx. :+1:

**Comment by ryrun** [comment]
@purcell: Do you have a tip for me? emacs brings me an error, when it was restarted and i try to open kix files. `(void-function kixtart-gen-regexp-list)` It seems i did something wrong with autoload tag feature of package.el?

**Comment by purcell** [comment]
Perhaps just move the contents of the `eval-and-compile` block to the top level. It's not obvious to me why those lines are wrapped in that form.

**Comment by ryrun** [comment]
Was inspired by other major mode packages :D I'll try, thx anyway.

**Pull request merged**
